### ISSUE TITLE
View by author not working :/

### ISSUE THREAD

**Issue by Dan503** [pvorb/npm-stat.com#60] opened 2018-06-17 06:01 UTC
I tried looking up my downloads stats
https://npm-stat.com/charts.html?author=dan503&from=2016-11-01

It came back with this error:
```
Could not fetch data. Does that package exist? 
Case matters. feign.FeignException:
status 404 reading AuthorsClient#browseAuthors(String,String); content:
```

As you can see here, the dan503 author most definitly exists:
https://www.npmjs.com/~dan503

**Comment by pvorb** [comment] 2018-06-17 23:04
Duplicate of #58

**Closed by pvorb** 2018-06-17 23:04 UTC
