### ISSUE TITLE
Wrong date label in tooltip

### ISSUE THREAD

**Issue by 19majkel94** [pvorb/npm-stat.com#70] opened 2018-10-03 15:35 UTC
![image](https://user-images.githubusercontent.com/10618781/46421537-93fe2a00-c732-11e8-92b9-a4805c6ba872.png)

The point for October 1 shows value for September 30 😕 

https://npm-stat.com/charts.html?package=type-graphql&from=2018-08-15&to=2018-10-04

**Comment by pvorb** [comment] 2018-10-03 15:37
Closing as duplicate of #43

**Closed by pvorb** 2018-10-03 15:37 UTC
