### ISSUE TITLE
npm-stat.com is down

### ISSUE THREAD

**Issue by limonte** [pvorb/npm-stat.com#78] opened 2019-04-19 10:44 UTC
https://downforeveryoneorjustme.com/npm-stat.com

![image](https://user-images.githubusercontent.com/6059356/56420998-21593400-62a9-11e9-8cb3-4ecc6b8dfb08.png)

https://travis-ci.org/sweetalert2/sweetalert2.github.io/builds/521874516

![image](https://user-images.githubusercontent.com/6059356/56421017-4057c600-62a9-11e9-8425-aed5915d9549.png)

**Comment by limonte** [comment] 2019-04-19 10:46
You might want to use some service like https://uptimerobot.com/ it's free for checks every 5 minutes.

**Comment by pvorb** [comment] 2019-04-19 15:08
I'm already using it, but it doesn't magically bring the site up again. Duplicate of #77.

**Closed by pvorb** 2019-04-19 15:08 UTC

**Comment by limonte** [comment] 2019-04-19 17:15
> but it doesn't magically bring the site up again.

I would love that kind of service 😁
